name: Mirror to GitLab

on:
  push:
    tags:
      - "v*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/Sheptykin/gitlab-component-manager.git"
          git push gitlab --mirror
